const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];$('#year').textContent=new Date().getFullYear();
$('#menu').onclick=()=>$('#links').classList.toggle('open');$$('#links a').forEach(a=>a.onclick=()=>$('#links').classList.remove('open'));
function esc(v=''){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function thumb(u){const m=(u||'').match(/embed\/([^?&]+)/);return m?`https://img.youtube.com/vi/${m[1]}/hqdefault.jpg`:''}
function render(filter='all'){const grid=$('#projects'),items=projects.filter(p=>filter==='all'||p.category.includes(filter));grid.innerHTML='';$('#empty').hidden=items.length>0;items.forEach(p=>{const el=document.createElement('article');el.className='project reveal show';const im=p.thumbnail||thumb(p.video);el.innerHTML=`<div class="media">${im?`<img src="${im}" alt="${esc(p.title)}" loading="lazy">`:''}<span class="label">${esc(p.label)}</span><span class="play">▶</span></div><div class="project-body"><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p><div class="tags">${p.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="meta"><span>${esc(p.date||'Project')}</span><span>↗</span></div></div>`;el.onclick=()=>openProject(p);grid.appendChild(el)})}
function openProject(p){$('#mcat').textContent=p.label;$('#mtitle').textContent=p.title;$('#mdesc').textContent=p.description;$('#mtags').innerHTML=p.tags.map(t=>`<span>${esc(t)}</span>`).join('');const box=$('#video');box.className='modal-video';box.innerHTML='';if((p.videoType==='youtube'||p.videoType==='vimeo')&&p.video){const f=document.createElement('iframe');f.src=p.video;f.allow='autoplay; fullscreen; picture-in-picture';f.allowFullscreen=true;box.appendChild(f)}else if(p.videoType==='local'&&p.video){const v=document.createElement('video');v.controls=true;v.src=p.video;box.appendChild(v)}else box.innerHTML='<div class="placeholder">Add your OBS Studio video URL in <b>projects.js</b> to show the walkthrough here.</div>';const l=$('#mlink');l.hidden=!p.link;if(p.link)l.href=p.link;$('#modal').classList.add('open');document.body.classList.add('lock')}
function close(){ $('#modal').classList.remove('open');document.body.classList.remove('lock');$('#video').innerHTML=''}$('#close').onclick=close;$('#backdrop').onclick=close;document.onkeydown=e=>e.key==='Escape'&&close();
$$('#filters button').forEach(b=>b.onclick=()=>{$$('#filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');obs.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(e=>obs.observe(e));
addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;$('#progress').style.width=(h?scrollY/h*100:0)+'%' });render();
